#!/usr/bin/env bash
# Configures new ubuntu machine
# Installs Nginx listening on port 80
# Serves page that returns Hello World! string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up server.\n"

# Starts Nginx service
sudo service nginx start

# Allows Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
#

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creates new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Sets up redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarts Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
