#!/usr/bin/env bash
# displays 1 - 100
# fizzBuzz when a multiple of 3 & 5
# fizz when a multiple of 3
# Buzz when a multiple of 5
count=0
while [ $count -lt 100 ]
do

	if (($count % 3 == 0 && $count % 5 == 0)); then
		echo "FizzBuzz"
	elif (($count % 3 == 0)); then
		echo "Fizz"
	elif (($count % 5 == 0)); then
		echo "Buzz"
	else
		echo $count
	fi
	((count++))
done
