#!/usr/bin/env bash
# Script that displays bad luck for the 4th iteration, and good luck for the 8th iteratio and the rest good luck
count=0
while [ $count -lt 10 ]
do
if [ $count -eq 3 ]
then
echo "bad luck"
elif [ $count -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((count++))
done
