#!/usr/bin/env bash
# displays numbers from 1 - 20
count=1
while [ $count -lt 21 ]
do
if [ $count -eq 4 ]
then
echo $count
echo 'bad luck from China'
elif [ $count -eq 9 ]
then
echo $count
echo 'bad luck from Japan'
elif [ $count -eq 17 ]
then
echo $count
echo 'bad luck from Italy'
else
echo $count

fi
((count++))
done
