#!/usr/bin/env bash
# Script that displays hour from 0 to 12
# Display minutes from 1 to 59
count=1
hour=0
echo "${hour} Hour"
while [ $hour -lt 2 ]
do
    echo $count

    if [ $count -eq 59 ]; then
        hour=$((hour + 1))
        if [ $hour -lt 2 ]; then
            echo "${hour} Hour"
            count=1
            while [ $count -le 12 ]
            do
                echo $count
                ((count++))
            done
        fi
        break
    fi

    ((count++))
done

