#!/usr/bin/env bash
# Displays the content of the current directory
# in a list format where the name part of the name 
# after the first dash is displayed
list=$(ls)
for l in $list;
do
echo "$l" | cut -d '-' -f2
done
