#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts /etc/hosts_backup
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' /etc/hosts_backup
cp -f /etc/hosts_backup /etc/hosts
