#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on

# Use ifconfig to get network interface information and grep for IPv4 addresses
ip -o -4 addr show | awk '{print $4}' | cut -d'/' -f1