#!/usr/bin/env bash
# Bash script that configures the container to fit the below requirements
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
